name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run Tests (if any)
      run: |
        echo "No tests configured" 

    - name: Build Docker Image
      run: |
        docker build -t your-dockerhub-username/ai-voice-assistant:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push your-dockerhub-username/ai-voice-assistant:latest
